//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Elmah.EntityFrameworkContext
{
    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.Options;

    public partial class ElmahModelEntities : DbContext
    {
        public IOptions<Elmah.EntityFrameworkContext.ConnectionStringOption> ConnectionStringOptions { get; private set; }

        public ElmahModelEntities()
        {
        }

        public ElmahModelEntities(DbContextOptions<ElmahModelEntities> options)
            : base(options)
        {
        }

        public ElmahModelEntities(IOptions<Elmah.EntityFrameworkContext.ConnectionStringOption> conStrOptions, DbContextOptions<ElmahModelEntities> options)
            : base(options)
        {
            ConnectionStringOptions = conStrOptions;
        }

        public DbSet<ELMAH_Error> ELMAH_Error { get; set; }

        public DbSet<ElmahApplication> ElmahApplication { get; set; }

        public DbSet<ElmahHost> ElmahHost { get; set; }

        public DbSet<ElmahSource> ElmahSource { get; set; }

        public DbSet<ElmahStatusCode> ElmahStatusCode { get; set; }

        public DbSet<ElmahType> ElmahType { get; set; }

        public DbSet<ElmahUser> ElmahUser { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer(ConnectionStringOptions.Value.ConnectionString, x => x.UseNetTopologySuite());
            }
        }

        /// <summary>
        /// {D255958A-8513-4226-94B9-080D98F904A1}Override this method to further configure the model that was discovered by convention from the entity types
        /// {D255958A-8513-4226-94B9-080D98F904A1}exposed in <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> properties on your derived context. The resulting model may be cached
        /// {D255958A-8513-4226-94B9-080D98F904A1}and re-used for subsequent instances of your derived context.
        /// </summary>
        /// <param name="modelBuilder">{D255958A-8513-4226-94B9-080D98F904A1}The builder being used to construct the model for this context. Databases (and other extensions) typically
        /// {D255958A-8513-4226-94B9-080D98F904A1}define extension methods on this object that allow you to configure aspects of the model that are specific
        /// {D255958A-8513-4226-94B9-080D98F904A1}to a given database.</param>
        /// <remarks>
        /// {D255958A-8513-4226-94B9-080D98F904A1}If a model is explicitly set on the options for this context (via <see cref="M:Microsoft.EntityFrameworkCore.DbContextOptionsBuilder.UseModel(Microsoft.EntityFrameworkCore.Metadata.IModel)" />)
        /// {D255958A-8513-4226-94B9-080D98F904A1}then this method will not be run.
        /// </remarks>
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            #region #1.1 ElmahModel.ELMAH_Error

            modelBuilder.Entity<ELMAH_Error>(entity =>
            {

                entity.ToTable("ELMAH_Error", "dbo");

                entity.HasKey(e => new { e.ErrorId })
                    .HasName("PK_ELMAH_Error_ErrorId");

                entity.Property(e => e.ErrorId)
                    .HasColumnName("ErrorId")
                    .ValueGeneratedNever();

                entity.Property(e => e.Application)
                    .HasColumnName("Application")
                    .IsRequired()
                    .HasMaxLength(60);

                entity.Property(e => e.Host)
                    .HasColumnName("Host")
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Type)
                    .HasColumnName("Type")
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.Source)
                    .HasColumnName("Source")
                    .IsRequired()
                    .HasMaxLength(60);

                entity.Property(e => e.Message)
                    .HasColumnName("Message")
                    .IsRequired()
                    .HasMaxLength(500);

                entity.Property(e => e.User)
                    .HasColumnName("User")
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.StatusCode)
                    .HasColumnName("StatusCode");

                entity.Property(e => e.TimeUtc)
                    .HasColumnName("TimeUtc")
                    .HasColumnType("DateTime");

                entity.Property(e => e.Sequence)
                    .HasColumnName("Sequence")
                    .ValueGeneratedOnAdd();

                entity.Property(e => e.AllXml)
                    .HasColumnName("AllXml")
                    .IsRequired();

                entity.HasOne(d => d.ElmahApplication)
                    .WithMany(p => p.ELMAH_Error)
                    .HasForeignKey(d => d.Application)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.ElmahHost)
                    .WithMany(p => p.ELMAH_Error)
                    .HasForeignKey(d => d.Host)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.ElmahSource)
                    .WithMany(p => p.ELMAH_Error)
                    .HasForeignKey(d => d.Source)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.ElmahStatusCode)
                    .WithMany(p => p.ELMAH_Error)
                    .HasForeignKey(d => d.StatusCode)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.ElmahType)
                    .WithMany(p => p.ELMAH_Error)
                    .HasForeignKey(d => d.Type)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.ElmahUser)
                    .WithMany(p => p.ELMAH_Error)
                    .HasForeignKey(d => d.User)
                    .OnDelete(DeleteBehavior.ClientSetNull);

            });

            #endregion #1.1 ElmahModel.ELMAH_Error

            #region #1.2 ElmahModel.ElmahApplication

            modelBuilder.Entity<ElmahApplication>(entity =>
            {

                entity.ToTable("ElmahApplication", "dbo");

                entity.HasKey(e => new { e.Application })
                    .HasName("PK_ElmahApplication_Application");

                entity.Property(e => e.Application)
                    .HasColumnName("Application")
                    .IsRequired()
                    .ValueGeneratedNever()
                    .HasMaxLength(60);

            });

            #endregion #1.2 ElmahModel.ElmahApplication

            #region #1.3 ElmahModel.ElmahHost

            modelBuilder.Entity<ElmahHost>(entity =>
            {

                entity.ToTable("ElmahHost", "dbo");

                entity.HasKey(e => new { e.Host })
                    .HasName("PK_ElmahHost_Host");

                entity.Property(e => e.Host)
                    .HasColumnName("Host")
                    .IsRequired()
                    .ValueGeneratedNever()
                    .HasMaxLength(50);

            });

            #endregion #1.3 ElmahModel.ElmahHost

            #region #1.4 ElmahModel.ElmahSource

            modelBuilder.Entity<ElmahSource>(entity =>
            {

                entity.ToTable("ElmahSource", "dbo");

                entity.HasKey(e => new { e.Source })
                    .HasName("PK_ElmahSource_Source");

                entity.Property(e => e.Source)
                    .HasColumnName("Source")
                    .IsRequired()
                    .ValueGeneratedNever()
                    .HasMaxLength(60);

            });

            #endregion #1.4 ElmahModel.ElmahSource

            #region #1.5 ElmahModel.ElmahStatusCode

            modelBuilder.Entity<ElmahStatusCode>(entity =>
            {

                entity.ToTable("ElmahStatusCode", "dbo");

                entity.HasKey(e => new { e.StatusCode })
                    .HasName("PK_ElmahStatusCode_StatusCode");

                entity.Property(e => e.StatusCode)
                    .HasColumnName("StatusCode")
                    .ValueGeneratedNever();

                entity.Property(e => e.Name)
                    .HasColumnName("Name")
                    .HasMaxLength(50);

            });

            #endregion #1.5 ElmahModel.ElmahStatusCode

            #region #1.6 ElmahModel.ElmahType

            modelBuilder.Entity<ElmahType>(entity =>
            {

                entity.ToTable("ElmahType", "dbo");

                entity.HasKey(e => new { e.Type })
                    .HasName("PK_ElmahType_Type");

                entity.Property(e => e.Type)
                    .HasColumnName("Type")
                    .IsRequired()
                    .ValueGeneratedNever()
                    .HasMaxLength(100);

            });

            #endregion #1.6 ElmahModel.ElmahType

            #region #1.7 ElmahModel.ElmahUser

            modelBuilder.Entity<ElmahUser>(entity =>
            {

                entity.ToTable("ElmahUser", "dbo");

                entity.HasKey(e => new { e.User })
                    .HasName("PK_ElmahUser_User");

                entity.Property(e => e.User)
                    .HasColumnName("User")
                    .IsRequired()
                    .ValueGeneratedNever()
                    .HasMaxLength(50);

            });

            #endregion #1.7 ElmahModel.ElmahUser

        }

    }
}

