//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elmah.Resx {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elmah.Resx.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Error Id"".
        /// </summary>
        public static string ErrorId {
            get {
                return ResourceManager.GetString("ErrorId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ErrorId is required"".
        /// </summary>
        public static string ErrorId_is_required {
            get {
                return ResourceManager.GetString("ErrorId_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Elmah Application"".
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Application should be 1 to 60"".
        /// </summary>
        public static string The_length_of_Application_should_be_1_to_60 {
            get {
                return ResourceManager.GetString("The_length_of_Application_should_be_1_to_60", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Elmah Host"".
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Host should be 1 to 50"".
        /// </summary>
        public static string The_length_of_Host_should_be_1_to_50 {
            get {
                return ResourceManager.GetString("The_length_of_Host_should_be_1_to_50", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Elmah Type"".
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Type should be 1 to 100"".
        /// </summary>
        public static string The_length_of_Type_should_be_1_to_100 {
            get {
                return ResourceManager.GetString("The_length_of_Type_should_be_1_to_100", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Elmah Source"".
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Source should be 1 to 60"".
        /// </summary>
        public static string The_length_of_Source_should_be_1_to_60 {
            get {
                return ResourceManager.GetString("The_length_of_Source_should_be_1_to_60", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Message"".
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Message should be 1 to 500"".
        /// </summary>
        public static string The_length_of_Message_should_be_1_to_500 {
            get {
                return ResourceManager.GetString("The_length_of_Message_should_be_1_to_500", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Elmah User"".
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of User should be 1 to 50"".
        /// </summary>
        public static string The_length_of_User_should_be_1_to_50 {
            get {
                return ResourceManager.GetString("The_length_of_User_should_be_1_to_50", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Elmah Status Code"".
        /// </summary>
        public static string StatusCode {
            get {
                return ResourceManager.GetString("StatusCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "StatusCode is required"".
        /// </summary>
        public static string StatusCode_is_required {
            get {
                return ResourceManager.GetString("StatusCode_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Time Utc"".
        /// </summary>
        public static string TimeUtc {
            get {
                return ResourceManager.GetString("TimeUtc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "TimeUtc is required"".
        /// </summary>
        public static string TimeUtc_is_required {
            get {
                return ResourceManager.GetString("TimeUtc_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sequence"".
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "All Xml"".
        /// </summary>
        public static string AllXml {
            get {
                return ResourceManager.GetString("AllXml", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of AllXml should be 1 to "".
        /// </summary>
        public static string The_length_of_AllXml_should_be_1_to_ {
            get {
                return ResourceManager.GetString("The_length_of_AllXml_should_be_1_to_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value"".
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Elmah Application"".
        /// </summary>
        public static string ElmahApplication {
            get {
                return ResourceManager.GetString("ElmahApplication", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Identifier In String"".
        /// </summary>
        public static string IdentifierInString {
            get {
                return ResourceManager.GetString("IdentifierInString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Pub Date"".
        /// </summary>
        public static string PubDate {
            get {
                return ResourceManager.GetString("PubDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Elmah Host"".
        /// </summary>
        public static string ElmahHost {
            get {
                return ResourceManager.GetString("ElmahHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Elmah Type"".
        /// </summary>
        public static string ElmahType {
            get {
                return ResourceManager.GetString("ElmahType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Elmah Source"".
        /// </summary>
        public static string ElmahSource {
            get {
                return ResourceManager.GetString("ElmahSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Elmah User"".
        /// </summary>
        public static string ElmahUser {
            get {
                return ResourceManager.GetString("ElmahUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Elmah Status Code"".
        /// </summary>
        public static string ElmahStatusCode {
            get {
                return ResourceManager.GetString("ElmahStatusCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Title"".
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Spatial Location"".
        /// </summary>
        public static string SpatialLocation {
            get {
                return ResourceManager.GetString("SpatialLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Name should be 0 to 50"".
        /// </summary>
        public static string The_length_of_Name_should_be_0_to_50 {
            get {
                return ResourceManager.GetString("The_length_of_Name_should_be_0_to_50", resourceCulture);
            }
        }

    }
}

