//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elmah.PetStore.Resx {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStringResource {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStringResource() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elmah.PetStore.Resx.UIStringResource", typeof(UIStringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Order"".
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Orders"".
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Id is required"".
        /// </summary>
        public static string Id_is_required {
            get {
                return ResourceManager.GetString("Id_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "PetId"".
        /// </summary>
        public static string PetId {
            get {
                return ResourceManager.GetString("PetId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "PetId is required"".
        /// </summary>
        public static string PetId_is_required {
            get {
                return ResourceManager.GetString("PetId_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Quantity"".
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Quantity is required"".
        /// </summary>
        public static string Quantity_is_required {
            get {
                return ResourceManager.GetString("Quantity_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ShipDate"".
        /// </summary>
        public static string ShipDate {
            get {
                return ResourceManager.GetString("ShipDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ShipDate is required"".
        /// </summary>
        public static string ShipDate_is_required {
            get {
                return ResourceManager.GetString("ShipDate_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Status"".
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Status is required"".
        /// </summary>
        public static string Status_is_required {
            get {
                return ResourceManager.GetString("Status_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Complete"".
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Complete is required"".
        /// </summary>
        public static string Complete_is_required {
            get {
                return ResourceManager.GetString("Complete_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Customer"".
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Customers"".
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Username"".
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Username is required"".
        /// </summary>
        public static string Username_is_required {
            get {
                return ResourceManager.GetString("Username_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Address"".
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Address is required"".
        /// </summary>
        public static string Address_is_required {
            get {
                return ResourceManager.GetString("Address_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Addresses"".
        /// </summary>
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Street"".
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Street is required"".
        /// </summary>
        public static string Street_is_required {
            get {
                return ResourceManager.GetString("Street_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "City"".
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "City is required"".
        /// </summary>
        public static string City_is_required {
            get {
                return ResourceManager.GetString("City_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "State"".
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "State is required"".
        /// </summary>
        public static string State_is_required {
            get {
                return ResourceManager.GetString("State_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Zip"".
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Zip is required"".
        /// </summary>
        public static string Zip_is_required {
            get {
                return ResourceManager.GetString("Zip_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Category"".
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Categories"".
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Name is required"".
        /// </summary>
        public static string Name_is_required {
            get {
                return ResourceManager.GetString("Name_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "User"".
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Users"".
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "FirstName"".
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "FirstName is required"".
        /// </summary>
        public static string FirstName_is_required {
            get {
                return ResourceManager.GetString("FirstName_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "LastName"".
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "LastName is required"".
        /// </summary>
        public static string LastName_is_required {
            get {
                return ResourceManager.GetString("LastName_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Email"".
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Email is required"".
        /// </summary>
        public static string Email_is_required {
            get {
                return ResourceManager.GetString("Email_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Password"".
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Password is required"".
        /// </summary>
        public static string Password_is_required {
            get {
                return ResourceManager.GetString("Password_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Phone"".
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Phone is required"".
        /// </summary>
        public static string Phone_is_required {
            get {
                return ResourceManager.GetString("Phone_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "UserStatus"".
        /// </summary>
        public static string UserStatus {
            get {
                return ResourceManager.GetString("UserStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "UserStatus is required"".
        /// </summary>
        public static string UserStatus_is_required {
            get {
                return ResourceManager.GetString("UserStatus_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tag"".
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tags"".
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Pet"".
        /// </summary>
        public static string Pet {
            get {
                return ResourceManager.GetString("Pet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Pets"".
        /// </summary>
        public static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Category is required"".
        /// </summary>
        public static string Category_is_required {
            get {
                return ResourceManager.GetString("Category_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "PhotoUrls"".
        /// </summary>
        public static string PhotoUrls {
            get {
                return ResourceManager.GetString("PhotoUrls", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "PhotoUrls is required"".
        /// </summary>
        public static string PhotoUrls_is_required {
            get {
                return ResourceManager.GetString("PhotoUrls_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tags is required"".
        /// </summary>
        public static string Tags_is_required {
            get {
                return ResourceManager.GetString("Tags_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ApiResponse"".
        /// </summary>
        public static string ApiResponse {
            get {
                return ResourceManager.GetString("ApiResponse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ApiResponses"".
        /// </summary>
        public static string ApiResponses {
            get {
                return ResourceManager.GetString("ApiResponses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Code"".
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Code is required"".
        /// </summary>
        public static string Code_is_required {
            get {
                return ResourceManager.GetString("Code_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Type"".
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Type is required"".
        /// </summary>
        public static string Type_is_required {
            get {
                return ResourceManager.GetString("Type_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Message"".
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Message is required"".
        /// </summary>
        public static string Message_is_required {
            get {
                return ResourceManager.GetString("Message_is_required", resourceCulture);
            }
        }

    }
}

