//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elmah.Resx {
    using System;
    using System.Reflection;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStringResourcePerApp {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public UIStringResourcePerApp() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elmah.Resx.UIStringResourcePerApp", typeof(UIStringResourcePerApp).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Elmah"".
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ELMAH_Error"".
        /// </summary>
        public static string ELMAH_Error {
            get {
                return ResourceManager.GetString("ELMAH_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Loading ELMAH_Error ..."".
        /// </summary>
        public static string Loading_ELMAH_Error____ {
            get {
                return ResourceManager.GetString("Loading_ELMAH_Error____", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please select ELMAH_Error ..."".
        /// </summary>
        public static string Please_select_ELMAH_Error____ {
            get {
                return ResourceManager.GetString("Please_select_ELMAH_Error____", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ElmahApplication"".
        /// </summary>
        public static string ElmahApplication {
            get {
                return ResourceManager.GetString("ElmahApplication", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Loading ElmahApplication ..."".
        /// </summary>
        public static string Loading_ElmahApplication____ {
            get {
                return ResourceManager.GetString("Loading_ElmahApplication____", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please select ElmahApplication ..."".
        /// </summary>
        public static string Please_select_ElmahApplication____ {
            get {
                return ResourceManager.GetString("Please_select_ElmahApplication____", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ElmahHost"".
        /// </summary>
        public static string ElmahHost {
            get {
                return ResourceManager.GetString("ElmahHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Loading ElmahHost ..."".
        /// </summary>
        public static string Loading_ElmahHost____ {
            get {
                return ResourceManager.GetString("Loading_ElmahHost____", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please select ElmahHost ..."".
        /// </summary>
        public static string Please_select_ElmahHost____ {
            get {
                return ResourceManager.GetString("Please_select_ElmahHost____", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ElmahSource"".
        /// </summary>
        public static string ElmahSource {
            get {
                return ResourceManager.GetString("ElmahSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Loading ElmahSource ..."".
        /// </summary>
        public static string Loading_ElmahSource____ {
            get {
                return ResourceManager.GetString("Loading_ElmahSource____", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please select ElmahSource ..."".
        /// </summary>
        public static string Please_select_ElmahSource____ {
            get {
                return ResourceManager.GetString("Please_select_ElmahSource____", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ElmahStatusCode"".
        /// </summary>
        public static string ElmahStatusCode {
            get {
                return ResourceManager.GetString("ElmahStatusCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Loading ElmahStatusCode ..."".
        /// </summary>
        public static string Loading_ElmahStatusCode____ {
            get {
                return ResourceManager.GetString("Loading_ElmahStatusCode____", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please select ElmahStatusCode ..."".
        /// </summary>
        public static string Please_select_ElmahStatusCode____ {
            get {
                return ResourceManager.GetString("Please_select_ElmahStatusCode____", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ElmahType"".
        /// </summary>
        public static string ElmahType {
            get {
                return ResourceManager.GetString("ElmahType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Loading ElmahType ..."".
        /// </summary>
        public static string Loading_ElmahType____ {
            get {
                return ResourceManager.GetString("Loading_ElmahType____", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please select ElmahType ..."".
        /// </summary>
        public static string Please_select_ElmahType____ {
            get {
                return ResourceManager.GetString("Please_select_ElmahType____", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ElmahUser"".
        /// </summary>
        public static string ElmahUser {
            get {
                return ResourceManager.GetString("ElmahUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Loading ElmahUser ..."".
        /// </summary>
        public static string Loading_ElmahUser____ {
            get {
                return ResourceManager.GetString("Loading_ElmahUser____", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please select ElmahUser ..."".
        /// </summary>
        public static string Please_select_ElmahUser____ {
            get {
                return ResourceManager.GetString("Please_select_ElmahUser____", resourceCulture);
            }
        }

    }
}

