//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elmah.Resx.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elmah.Resx.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Xml.
        /// </summary>
        public static string AllXml {
            get {
                return ResourceManager.GetString("AllXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmah Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_this_ {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delete_this?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string Back_to_List {
            get {
                return ResourceManager.GetString("Back_to_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Create_New {
            get {
                return ResourceManager.GetString("Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmah Application.
        /// </summary>
        public static string ElmahApplication {
            get {
                return ResourceManager.GetString("ElmahApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmah Host.
        /// </summary>
        public static string ElmahHost {
            get {
                return ResourceManager.GetString("ElmahHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmah Source.
        /// </summary>
        public static string ElmahSource {
            get {
                return ResourceManager.GetString("ElmahSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmah Status Code.
        /// </summary>
        public static string ElmahStatusCode {
            get {
                return ResourceManager.GetString("ElmahStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmah Type.
        /// </summary>
        public static string ElmahType {
            get {
                return ResourceManager.GetString("ElmahType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmah User.
        /// </summary>
        public static string ElmahUser {
            get {
                return ResourceManager.GetString("ElmahUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Id.
        /// </summary>
        public static string ErrorId {
            get {
                return ResourceManager.GetString("ErrorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorId is required.
        /// </summary>
        public static string ErrorId_is_required {
            get {
                return ResourceManager.GetString("ErrorId_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Csv.
        /// </summary>
        public static string ExportToCsv {
            get {
                return ResourceManager.GetString("ExportToCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- All {0} --.
        /// </summary>
        public static string Format_All {
            get {
                return ResourceManager.GetString("Format_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Items Per Page.
        /// </summary>
        public static string Format_ItemsPerPage {
            get {
                return ResourceManager.GetString("Format_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Please Select {0} --.
        /// </summary>
        public static string Format_Please_Select {
            get {
                return ResourceManager.GetString("Format_Please_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmah Host.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier In String.
        /// </summary>
        public static string IdentifierInString {
            get {
                return ResourceManager.GetString("IdentifierInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string PreDefinedDateTimeRanges_Custom {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Five Years.
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastFiveYears {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastFiveYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastMonth {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Six Months.
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastSixMonths {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastSixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Ten Years.
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastTenYears {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastTenYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Three Months.
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastThreeMonths {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastWeek {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastYear {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Five Years.
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextFiveYears {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextFiveYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Month.
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextMonth {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Six Months.
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextSixMonths {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextSixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Ten Years.
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextTenYears {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextTenYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Three Months.
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextThreeMonths {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Week.
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextWeek {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Year.
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextYear {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        public static string PreDefinedDateTimeRanges_ThisMonth {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        public static string PreDefinedDateTimeRanges_ThisWeek {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        public static string PreDefinedDateTimeRanges_ThisYear {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string PreDefinedDateTimeRanges_Today {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string PreDefinedDateTimeRanges_Tomorrow {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string PreDefinedDateTimeRanges_Yesterday {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pub Date.
        /// </summary>
        public static string PubDate {
            get {
                return ResourceManager.GetString("PubDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmah Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial Location.
        /// </summary>
        public static string SpatialLocation {
            get {
                return ResourceManager.GetString("SpatialLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmah Status Code.
        /// </summary>
        public static string StatusCode {
            get {
                return ResourceManager.GetString("StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusCode is required.
        /// </summary>
        public static string StatusCode_is_required {
            get {
                return ResourceManager.GetString("StatusCode_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of AllXml should be 1 to .
        /// </summary>
        public static string The_length_of_AllXml_should_be_1_to_ {
            get {
                return ResourceManager.GetString("The_length_of_AllXml_should_be_1_to_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of Application should be 1 to 60.
        /// </summary>
        public static string The_length_of_Application_should_be_1_to_60 {
            get {
                return ResourceManager.GetString("The_length_of_Application_should_be_1_to_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of Host should be 1 to 50.
        /// </summary>
        public static string The_length_of_Host_should_be_1_to_50 {
            get {
                return ResourceManager.GetString("The_length_of_Host_should_be_1_to_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of Message should be 1 to 500.
        /// </summary>
        public static string The_length_of_Message_should_be_1_to_500 {
            get {
                return ResourceManager.GetString("The_length_of_Message_should_be_1_to_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of Name should be 0 to 50.
        /// </summary>
        public static string The_length_of_Name_should_be_0_to_50 {
            get {
                return ResourceManager.GetString("The_length_of_Name_should_be_0_to_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of Source should be 1 to 60.
        /// </summary>
        public static string The_length_of_Source_should_be_1_to_60 {
            get {
                return ResourceManager.GetString("The_length_of_Source_should_be_1_to_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of Type should be 1 to 100.
        /// </summary>
        public static string The_length_of_Type_should_be_1_to_100 {
            get {
                return ResourceManager.GetString("The_length_of_Type_should_be_1_to_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of User should be 1 to 50.
        /// </summary>
        public static string The_length_of_User_should_be_1_to_50 {
            get {
                return ResourceManager.GetString("The_length_of_User_should_be_1_to_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Utc.
        /// </summary>
        public static string TimeUtc {
            get {
                return ResourceManager.GetString("TimeUtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeUtc is required.
        /// </summary>
        public static string TimeUtc_is_required {
            get {
                return ResourceManager.GetString("TimeUtc_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmah Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmah User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
